In [138]:
from jupyter_dash import JupyterDash
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from dash import dcc
from dash import html
from dash.dependencies import Input, Output

In [139]:
df = pd.read_pickle("census_name_percents.pkl")

In [140]:
FAVORITES = ['alta', 'lily', 'mirabelle', 'lyra', 
             'serena', 'ella', 'annika', 'edna', 
             'agata', 'ava', 'adie', 'daria', 'sofia', 
             'eleanore', 'lina', 'odette', 'tara', 'yuna', 
             'zoe', 'marina', 'aurora', 'cora', 'amira', 
             'juno', 'vienna', 'elina', 'lana', 'sona']
VOWELS = list("aeiouy")

In [141]:
first_letters = {x[0] for x in FAVORITES}

In [142]:
last_letters = ['a', 'e', 'o', 'y', 't', 'n', 'r']

In [143]:
# what is the proportion of vowels to consonants in the names we like?

favorites_letter_ratios = [(len([c for c in name if c in VOWELS]) / len(name)) 
                           for name in FAVORITES]

x = zip(favorites_letter_ratios, FAVORITES)

# for y in x:
#     print(y)

In [144]:
def get_vowel_ratio(name):
    return len([c for c in name if c in VOWELS]) / len(name)

In [145]:
# what do these favs have in common? =hardcoded filters on dataframe

df_filtered = df[(df['name'].str.contains(f'^[{"".join(first_letters)}]'))
                &
                (df['sex'] == 'F')
                &
                (df['name'].str.contains(f'[{"".join(last_letters)}]$'))
                
                &
                (df['name'].apply(get_vowel_ratio) >= 0.5) 
                 
                #todo maybe change this into a dash input
                &
                (df['name'].str.len() < 6)
                & 
                (df['name'].str.len() > 2)
                 
                
                ]
# .str.contains('|'.join(includeKeywords)

In [146]:
# add a column that has a number for upper third of its own 
# peak popularity value (or TF might work too)

# when is percent_of_births the highest for a name

# df_filtered["in_top_third_of_percent_range"] = df[df_filtered.percent_of_births.max()] 
#     / 3 > 0.33]

# df_filtered[df_filtered['in_top_third_of_percent_range']==df_filtered.groupby('name')['percent_of_births'].transform('max')]


# df_filtered['in_top_third_of_percent_range'] = df_filtered.groupby("name").percent_of_births.max()

df_percent_max = df_filtered.groupby("name").percent_of_births.max().reset_index()
df_percent_max = df_percent_max.rename({"percent_of_births": "max_percent_of_births"}, axis='columns')

In [147]:
df_filtered = df_filtered.merge(
    df_percent_max,
    on="name"
)

In [148]:
df_filtered = df_filtered[
    ((df_filtered.percent_of_births / df_filtered.max_percent_of_births) >= .33)
]

In [152]:
df_filtered["in_top_third"] = ((df_filtered.percent_of_births / df_filtered.max_percent_of_births) >= .33)

In [153]:
df_filtered

,year,name,sex,number,total_births_estimate,percent_of_births,max_percent_of_births,in_top_third
0,1880,leo,F,6,201484,0.002978,0.006154,True
1,1880,zoa,F,8,201484,0.003971,0.005340,True
2,1880,susie,F,361,201484,0.179171,0.218944,True
3,1880,abbie,F,71,201484,0.035239,0.046450,True
4,1880,effie,F,406,201484,0.201505,0.263202,True
...,...,...,...,...,...,...,...,...
65156,2020,taela,F,5,3305259,0.000151,0.000312,True
65157,2020,avea,F,13,3305259,0.000393,0.000465,True
65158,2020,leira,F,23,3305259,0.000696,0.000785,True
65159,2020,aiza,F,118,3305259,0.003570,0.003570,True
65160,2020,saiee,F,5,3305259,0.000151,0.000151,True

In [16]:
# WHAT DASHBOARD INPUTS DO WE WANT? 

# name length - already hardcoded but could still do this

# time shift from peak years of favs in years

# year (range beginning and end?)

# + percentage range? no, we're hardcoding top third

In [17]:
# different graph? 

# max percent

# average percent

# how many names that year

In [154]:
df_filtered = df_filtered.sort_values("year").reset_index(drop=True)

In [161]:
df_filtered[df_filtered.name == 'sage']

,year,name,sex,number,total_births_estimate,percent_of_births,max_percent_of_births,in_top_third
36695,1999,sage,F,521,3693307,0.014107,0.039362,True
37760,2000,sage,F,557,3779007,0.014739,0.039362,True
38895,2001,sage,F,589,3742401,0.015739,0.039362,True
39812,2002,sage,F,683,3737195,0.018276,0.039362,True
41504,2003,sage,F,748,3801147,0.019678,0.039362,True
43155,2004,sage,F,880,3819591,0.023039,0.039362,True
44592,2005,sage,F,868,3843322,0.022585,0.039362,True
45235,2006,sage,F,766,3954356,0.019371,0.039362,True
46281,2007,sage,F,683,3995740,0.017093,0.039362,True
47834,2008,sage,F,690,3928389,0.017564,0.039362,True
49991,2009,sage,F,793,3817731,0.020772,0.039362,True
50979,2010,sage,F,642,3693163,0.017383,0.039362,True
52244,2011,sage,F,646,3654691,0.017676,0.039362,True
53819,2012,sage,F,624,3653979,0.017077,0.039362,True
55556,2013,sage,F,666,3641604,0.018289,0.039362,True
55869,2014,sage,F,842,3701784,0.022746,0.039362,True
57436,2015,sage,F,887,3695531,0.024002,0.039362,True
59400,2016,sage,F,939,3662277,0.025640,0.039362,True
61109,2017,sage,F,1047,3568294,0.029342,0.039362,True
61691,2018,sage,F,1091,3505963,0.031118,0.039362,True
63307,2019,sage,F,1170,3455946,0.033855,0.039362,True
63865,2020,sage,F,1301,3305259,0.039362,0.039362,True

In [158]:
APP_NAME = "tester15"



# Build App
app = JupyterDash(__name__)
app.layout = html.Div([
    html.H1("Baby Names"),
    dcc.Graph(id=APP_NAME),
    html.Label([
        "year",
        dcc.Dropdown(
            id='year-dropdown', clearable=False,
            value="2020", options=[
                {'label': year, 'value': year}
                for year in sorted(list(set(df.year)))
            ]
        )
    ]),
    
    html.Label([
        "peak-percent",
        dcc.RangeSlider(
            id='peak-percent-slider',
            min=0,
            max=0.1,
            step=0.001,
            value=[0, 0.1],
            marks={
                0.0: '0.0',
                0.025: '0.025',
                0.05: '0.05',
                0.075: '0.075',
                0.1: '0.1'
            },
        ),
    ]),
    html.Label([
        "first_letter",
        dcc.Dropdown(
            id='first-letter-dropdown', clearable=False,
            value="v", options=[
                {'label': letter, 'value': letter}
                for letter in sorted(list(first_letters))
            ]
        )
    ]),
])

# Define callback to update graph
@app.callback(
    Output(APP_NAME, 'figure'),
    [Input("year-dropdown", "value"),
     Input("first-letter-dropdown", "value"),
     Input("peak-percent-slider", "value")]
)
def update_graph(year_selection, first_letter_selection, peak_percent_selection):
    names_to_show = set(df_filtered[(df_filtered["year"] == year_selection) 
                                    & (df_filtered["in_top_third"])
                                    & (df_filtered["name"].str.startswith(first_letter_selection))
                                    & (df_filtered["max_percent_of_births"] >= peak_percent_selection[0])
                                    & (df_filtered["max_percent_of_births"] <= peak_percent_selection[1])].name)
    
    traces = list()
    
    #todo: fix this hacky way to make the x-axis linear
    traces.append(go.Scatter(x=sorted(list(set(df_filtered.year))),
                             y=sorted(list(set(df_filtered.percent_of_births))),
                             name=""))
    
    for name in names_to_show:
        name_df = df[(df["name"] == name)]
        traces.append(go.Scatter(x=name_df.year,
                                 y=name_df.percent_of_births,
                                 name=name))
                                 
    
    #display_df = df[df["name"].isin(names)]
    
    return go.Figure(
        data=traces
    )

# Run app and display result inline in the notebook
app.run_server(mode='external')

Dash app running on http://127.0.0.1:8050/